routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('/blog')->group(function() {
    Route::get('/', 'BlogController@index')->name('blog.home');
    Route::get('/{id}','BlogController@post')->name('blog.post');
});

Route::prefix('/admin')->middleware('isLogin')->group(function () {
    Route::resource('/post','PostController');
    Route::resource('/catalog','CatalogController');
    Route::resource('/comment','CommentController');
});

Route::prefix('/member')->middleware("isLogin")->group(function(){
    Route::prefix('/api')->middleware('can:super-admin')->group(function(){
        Route::get('/show','ApiController@index')->name('api.show');
        Route::get('/showAdd','ApiController@showAdd')->name('api.showAdd');
        Route::post('/add','ApiController@add')->name('api.add');
    });
});

Route::prefix("/api")->group(function (){
    Route::post("/getPosts", "ApiController@getPosts")->name("api.getPosts");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    /**
        * @var  array $guarded
        */
    protected $guarded = [
        'id',
        'created_at',
        'updated_at'
    ];

    public function User()
    {
        return $this->belongsTo(User::class);
    }
	
	public function Comment()
	{
		return $this->hasMany(Comment::class);
	}

    public function Catalog()
    {
        return $this->belongsToMany(Catalog::class);
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Auth;
use App\Repositories\PostRepository;
use App\Repositories\UserRepository;
use App\Repositories\CatalogRepository;

class PostController extends Controller
{
    protected $postRepository;
    protected $userRepository;
    protected $catalogRepository;

    public function __construct(PostRepository $postRepository, UserRepository $userRepository, CatalogRepository $catalogRepository)
    {
        $this->postRepository = $postRepository;
        $this->userRepository = $userRepository;
        $this->catalogRepository = $catalogRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('post.index',[
            'posts' => $this->postRepository->paginate(5, ['Catalog', 'User'])
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create', [
            'users' => $this->userRepository->getAll(),
            'catalogs' => $this->catalogRepository->getAll()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //處理文章資料
        $this->postRepository->create([
            'user_id' => $request->input('user_id'),
            'title' => $request->input('title'),
            'content' => $request->input('content')
        ],
            $request->input('catalog')
        );

        return view('tpl.msg',[
            'title' => '發布成功！',
            'status' => 1,
            'msg' => '發布成功！'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('post.show',[
            'post' => $this->postRepository->getById($id, ['Catalog', 'User'])
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = $this->postRepository->getById($id, 'Catalog');

        $catalogList = [];
        foreach ($post->Catalog as $catalog) {
            array_push($catalogList, $catalog->id);
        }

        return view('post.edit',[
            'users' => $this->userRepository->getAll(),
            'post' => $post,
            'catalogs' => $this->catalogRepository->getAll(),
            'catalogList' => $catalogList
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->postRepository->update(
            $id, [
                'user_id' => $request->input('user_id'),
                'title' => $request->input('title'),
                'content' => $request->input('content')
            ],
            $request->input('catalog')
        );

        return view('tpl.msg',[
            'title' => '修改成功！',
            'status' => 1,
            'msg' => '修改成功！'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->postRepository->delete($id);

        return view('tpl.msg',[
            'title' => '刪除成功！',
            'status' => 1,
            'msg' => '刪除成功！'
        ]);
    }
}

resources/views/post/create.blade.php
@extends('tpl.main')

@section('title', 'New Post')

@section('content')
    <form action="{{ route('post.store') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="user_id">User id:</label>
            <select class="form-control" name="user_id" id="user_id">
                @foreach($users as $user)
                    @if($user->id == Auth::id()){{--預設選擇為當前使用者--}}
                        <option value="{{ $user->id }}" selected>{{ $user->name }}</option>
                    @else
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" class="form-control" placeholder="Post Title">
        </div>
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea name="content" id="content" class="form-control" rows="3" placeholder="Post Content"></textarea>
        </div>
        <div class="form-group">
            <label for="catalog">Catalog:</label>
            <select name="catalog[]" id="catalog" class="form-control" multiple>
                @foreach($catalogs as $catalog)
                    <option value="{{ $catalog->id }}">{{ $catalog->catalog_name }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
@endsection

resources/views/post/edit.blade.php
@extends('tpl.main')

@section('title', $post->title .' edit')

@section('content')
    <form action="{{ route('post.update', [ 'post' => $post->id ]) }}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="user_id">User id:</label>
            <select class="form-control" name="user_id" id="user_id">
                @foreach($users as $user)
                    @if($user->id == $post->user_id)
                        <option value="{{ $user->id }}" selected>{{ $user->name }}</option>
                    @else
                        <option value="{{ $user->id }}">{{ $user->name }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text" name="title" id="title" class="form-control" value="{{ $post->title }}">
        </div>
        <div class="form-group">
            <label for="content">Content:</label>
            <textarea name="content" id="content" class="form-control" rows="3">{{ $post->content }}</textarea>
        </div>
        <div class="form-group">
            <label for="catalog">Catalog:</label>
            <select name="catalog[]" id="catalog" class="form-control" multiple>
                @foreach($catalogs as $catalog)
                    @if(in_array($catalog->id, $catalogList))
                        <option value="{{ $catalog->id }}" selected>{{ $catalog->catalog_name }}</option>
                    @else
                        <option value="{{ $catalog->id }}">{{ $catalog->catalog_name }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="created_at">Created at:</label>
            <input type="text" name="created_at" id="created_at" class="form-control" value="{{ $post->created_at }}" readonly="readonly">
        </div>
        <div class="form-group">
            <label for="updated_at">Updated at:</label>
            <input type="text" name="updated_at" id="updated_at" class="form-control" value="{{ $post->updated_at }}" readonly="readonly'">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update!</button>
        </div>
    </form>
@endsection

resources/views/post/index.blade.php
@extends('tpl.main')

@section('title', 'All Posts')

@section('head')
    <script>
    function deleteCheck()
    {
        return confirm('確認要刪除嗎？');
    }
    </script>
@endsection

@section('content')
    @foreach($posts as $post)
        <table class="table table-bordered">
            <tr>
                <td>Title:</td>
                <td><a href="{{ route('post.show', [ 'post' => $post->id ]) }}">{{ $post->title }}</a></td>
            </tr>
            <tr>
                <td>Content:</td>
                <td>{{ $post->content }}</td>
            </tr>
            <tr>
                <td>Catalog:</td>
                <td>
                @foreach($post->Catalog as $cata)
                        <span class="badge badge-secondary" style="font-size:15px;">{{ $cata->catalog_name }}</span>
                @endforeach
                </td>
            </tr>
            <tr>
                <td>Posts Author:</td>
                <td>{{ $post->User->name }}</td>
            </tr>
            <tr>
                <td>Created at:</td>
                <td>{{ $post->created_at }}</td>
            </tr>
            <tr>
                <td>Last updated at:</td>
                <td>{{ $post->updated_at }}</td>
            </tr>
            <tr>
                <td>Action:</td>
                <td>
                    <form action="{{ route('post.destroy', [ 'post' => $post->id ]) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="button" onclick="document.location.href='{{ route('post.edit', ['post' => $post->id]) }}';" class="btn btn-warning"><i class="fa fa-edit"></i> 編輯</button>
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck()"><i class="fa fa-trash"></i> 刪除</button>
                    </form>
                </td>
            </tr>
        </table>
    @endforeach
    {{ $posts->links() }}
@endsection

resources/views/post/show.blade.php
@extends('tpl.main')

@section('title', $post->title)

@section('content')
    <table class="table table-bordered">
        <tr>
            <td>Posts ID:</td>
            <td>{{ $post->id }}</td>
        </tr>
        <tr>
            <td>Title:</td>
            <td>{{ $post->title }}</td>
        </tr>
        <tr>
            <td>Content:</td>
            <td>{{ $post->content }}</td>
        </tr>
        <tr>
            <td>Catalog:</td>
            <td>
                @foreach($post->Catalog as $cata)
                    <span class="badge badge-secondary" style="font-size:15px;">{{ $cata->catalog_name }}</span>
                @endforeach
            </td>
        </tr>
        <tr>
            <td>Posts Author:</td>
            <td>{{ $post->User->name }}</td>
        </tr>
        <tr>
            <td>Created at:</td>
            <td>{{ $post->created_at }}</td>
        </tr>
        <tr>
            <td>Last updated at:</td>
            <td>{{ $post->updated_at }}</td>
        </tr>
    </table>
@endsection