routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('/blog')->group(function() {
    Route::get('/', 'BlogController@index')->name('blog.home');
    Route::get('/{id}','BlogController@post')->name('blog.post');
});

Route::prefix('/admin')->middleware('isLogin')->group(function () {
    Route::resource('/post','PostController');
    Route::resource('/catalog','CatalogController');
    Route::resource('/comment','CommentController');
});

Route::prefix('/member')->middleware("isLogin")->group(function(){
    Route::prefix('/api')->middleware('can:super-admin')->group(function(){
        Route::get('/show','ApiController@index')->name('api.show');
        Route::get('/showAdd','ApiController@showAdd')->name('api.showAdd');
        Route::post('/add','ApiController@add')->name('api.add');
    });
});

Route::prefix("/api")->group(function (){
    Route::post("/getPosts", "ApiController@getPosts")->name("api.getPosts");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

resources/views/tpl/footer.blade.php
<address>
    <small>Powered By Ken Chang<br/>Webmaster: pp24513@changken.org</small>
</address>

resources/views/tpl/front-main.blade.php
<html lang="zh-TW">

<head>
    <title>@yield('title')</title>
    <meta charset="UTF-8">
    @include('tpl.head')
    @section('head')
    @show
</head>

<body>
    <div class="container">
        <h1 class="text-center">@yield('title')</h1>
        @include('tpl.front-nav')
        <hr>
        @yield('content')
        <hr>
        @include('tpl.footer')
    </div>
</body>

</html>

resources/views/tpl/front-nav.blade.php
<ul class="nav nav-tabs">
    <li class="nav-item">
        <a href="{{ route('blog.home') }}" class="nav-link">Blog</a>
    </li>
    @if(Auth::check())
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
               aria-expanded="false">
                admin <span class="caret"></span>
            </a>
            <div class="dropdown-menu">
                <a class="dropdown-item" href="{{ route('post.index') }}">Post List</a>
                <a class="dropdown-item" href="{{ route('catalog.index') }}">Catalog List</a>
                <a class="dropdown-item" href="{{ route('comment.index') }}">Comment List</a>
            </div>
        </li>
    @endif
</ul>

resources/views/tpl/head.blade.php
<link rel="stylesheet" href="{{ asset('/bootstrap/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset("/fontawesome/css/all.css") }}">
<link rel="stylesheet" href="{{ asset("/css/style.css") }}">
<script src="{{ asset('/js/jquery-3.3.1.min.js') }}"></script>
<script src="{{ asset('/js/popper.min.js') }}"></script>
<script src="{{ asset('/bootstrap/js/bootstrap.min.js') }}"></script>

resources/views/tpl/main.blade.php
<html lang="zh-TW">

<head>
    <title>@yield('title')</title>
    <meta charset="UTF-8">
    @include('tpl.head')
    @section('head')
    @show
</head>

<body>
    <div class="container">
        <h1 class="text-center">@yield('title')</h1>
        @include('tpl.nav')
        <hr>
        @yield('content')
        <hr>
        @include('tpl.footer')
    </div>
</body>

</html>

resources/views/tpl/msg.blade.php
@extends('tpl.main')

@section('title', $title)

@section('content')
    @if($status == 1)
        <div class="alert alert-success" role="alert">
            <p class="text-center">{{ $msg }}</p>
        </div>
    @else
        <div class="alert alert-danger" role="alert">
            <p class="text-center">{{ $msg }}</p>
        </div>
    @endif
@endsection

resources/views/tpl/nav.blade.php
<ul class="nav nav-tabs">
    <li class="nav-item"><a href="{{ route('blog.home') }}" class="nav-link">Blog</a></li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
            Post <span class="caret"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ route('post.index') }}">Post List</a>
            <a class="dropdown-item" href="{{ route('post.create') }}">Create Post</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
            Catalog <span class="caret"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ route('catalog.index') }}">Catalog List</a>
            <a class="dropdown-item" href="{{ route('catalog.create') }}">Create Catalog</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
            Comment <span class="caret"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ route('comment.index') }}">Comment List</a>
            <a class="dropdown-item" href="{{ route('comment.create') }}">Create Comment</a>
        </div>
    </li>
    <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true"
           aria-expanded="false">
            Api <span class="caret"></span>
        </a>
        <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ route('api.show') }}">Api List</a>
            <a class="dropdown-item" href="{{ route('api.showAdd') }}">Add Api Key</a>
        </div>
    </li>
</ul>