routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('/blog')->group(function() {
    Route::get('/', 'BlogController@index')->name('blog.home');
    Route::get('/{id}','BlogController@post')->name('blog.post');
});

Route::prefix('/admin')->middleware('isLogin')->group(function () {
    Route::resource('/post','PostController');
    Route::resource('/catalog','CatalogController');
    Route::resource('/comment','CommentController');
});

Route::prefix('/member')->middleware("isLogin")->group(function(){
    Route::prefix('/api')->middleware('can:super-admin')->group(function(){
        Route::get('/show','ApiController@index')->name('api.show');
        Route::get('/showAdd','ApiController@showAdd')->name('api.showAdd');
        Route::post('/add','ApiController@add')->name('api.add');
    });
});

Route::prefix("/api")->group(function (){
    Route::post("/getPosts", "ApiController@getPosts")->name("api.getPosts");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Catalog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Catalog extends Model
{
    /**
        * @var  array $guarded
        */
    protected $guarded = [
        'id',
        'created_at',
        'updated_at'
    ];

    public function Post()
    {
        return $this->belongsToMany(Post::class);
    }
}

app/Http/Controllers/CatalogController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\CatalogRepository;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    protected $catalogRepository;

    public function __construct(CatalogRepository $catalogRepository)
    {
        $this->catalogRepository = $catalogRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('catalog.index',[
            'catalogs' => $this->catalogRepository->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('catalog.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->catalogRepository->create([
            'catalog_name' => $request->input('catalog_name')
        ]);

        return view('tpl.msg', [
            'title' => '新增成功',
            'status' => 1,
            'msg' => '新增成功！'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('catalog.show',[
            'catalog' => $this->catalogRepository->getById($id, 'Post')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('catalog.edit', [
            'catalog' => $this->catalogRepository->getById($id)
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->catalogRepository->update($id,[
            'catalog_name' => $request->input('catalog_name')
        ]);

        return view('tpl.msg', [
            'title' => '修改成功',
            'status' => 1,
            'msg' => '修改成功！'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->catalogRepository->delete($id);

        return view('tpl.msg', [
            'title' => '刪除成功',
            'status' => 1,
            'msg' => '刪除成功！'
        ]);
    }
}

resources/views/catalog/create.blade.php
@extends('tpl.main')

@section('title', 'New Catalog')

@section('content')
    <form action="{{ route('catalog.store') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="catalog_name">Catalog Name:</label>
            <input type="text" name="catalog_name" id="catalog_name" class="form-control" placeholder="Catalog Name">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
@endsection

resources/views/catalog/edit.blade.php
@extends('tpl.main')

@section('title', $catalog->catalog_name . ' edit')

@section('content')
    <form action="{{ route('catalog.update', ['catalog' => $catalog->id]) }}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="id">Catalog ID:</label>
            <input type="text" name="id" id="id" class="form-control" value="{{ $catalog->id }}" readonly="readonly">
        </div>
        <div class="form-group">
            <label for="catalog_name">Catalog Name:</label>
            <input type="text" name="catalog_name" id="catalog_name" class="form-control" value="{{ $catalog->catalog_name }}">
        </div>
        <div class="form-group">
            <label for="id">Created at:</label>
            <input type="text" name="created_at" id="created_at" class="form-control" value="{{ $catalog->created_at }}" readonly="readonly">
        </div>
        <div class="form-group">
            <label for="id">Updated at:</label>
            <input type="text" name="updated_at" id="updated_at" class="form-control" value="{{ $catalog->updated_at }}" readonly="readonly">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Update!</button>
        </div>
    </form>
@endsection

resources/views/catalog/index.blade.php
@extends('tpl.main')

@section('title', 'All Catalogs')

@section('head')
    <script>
        function deleteCheck()
        {
            return confirm('確認要刪除嗎？');
        }
    </script>
@endsection

@section('content')
    @foreach($catalogs as $catalog)
        <table class="table table-bordered">
            <tr>
                <td>Catalog Name:</td>
                <td><a href="{{  route('catalog.show', ['catalog' => $catalog->id]) }}">{{ $catalog->catalog_name }}</a></td>
            </tr>
            <tr>
                <td>Created at:</td>
                <td>{{ $catalog->created_at }}</td>
            </tr>
            <tr>
                <td>Last updated at:</td>
                <td>{{ $catalog->updated_at }}</td>
            </tr>
            <tr>
                <td>Action:</td>
                <td>
                    <form action="{{ route('catalog.destroy', [ 'catalog' => $catalog->id ]) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="button" onclick="document.location.href='{{ route('catalog.edit', [ 'catalog' => $catalog->id ]) }}';" class="btn btn-warning"><i class="fa fa-edit"></i> 編輯</button>
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck()"><i class="fa fa-trash"></i> 刪除</button>
                    </form>
                </td>
            </tr>
        </table>
    @endforeach
    {{ $catalogs->links() }}
@endsection

resources/views/catalog/show.blade.php
@extends('tpl.main')

@section('title', $catalog->catalog_name)

@section('content')
    <table class="table table-bordered">
        <tr>
            <td>Catalog ID:</td>
            <td>{{ $catalog->id }}</td>
        </tr>
        <tr>
            <td>Catalog Name:</td>
            <td>{{ $catalog->catalog_name }}</td>
        </tr>
        <tr>
            <td>Amount:</td>
            <td>{{ $catalog->Post()->count() }}</td>
        </tr>
        <tr>
            <td>Created at:</td>
            <td>{{ $catalog->created_at }}</td>
        </tr>
        <tr>
            <td>Last updated at:</td>
            <td>{{ $catalog->updated_at }}</td>
        </tr>
    </table>
    <table class="table table-bordered text-center mx-auto w-75">
        <thead class="thead-dark">
            <tr>
                <th colspan="2">Associate Post List</th>
            </tr>
        </thead>
        <tbody>
        <tr>
            <td>Post ID</td>
            <td>Post Title</td>
        </tr>
            @foreach($catalog->Post as $post)
                <tr>
                    <td>{{ $post->id }}</td>
                    <td><a href="{{ route('post.show', [ 'post' => $post->id ]) }}" target="_blank">{{ $post->title }}</a></td>
                </tr>
            @endforeach
        </tbody>
    </table>
@endsection