routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('/blog')->group(function() {
    Route::get('/', 'BlogController@index')->name('blog.home');
    Route::get('/{id}','BlogController@post')->name('blog.post');
});

Route::prefix('/admin')->middleware('isLogin')->group(function () {
    Route::resource('/post','PostController');
    Route::resource('/catalog','CatalogController');
    Route::resource('/comment','CommentController');
});

Route::prefix('/member')->middleware("isLogin")->group(function(){
    Route::prefix('/api')->middleware('can:super-admin')->group(function(){
        Route::get('/show','ApiController@index')->name('api.show');
        Route::get('/showAdd','ApiController@showAdd')->name('api.showAdd');
        Route::post('/add','ApiController@add')->name('api.add');
    });
});

Route::prefix("/api")->group(function (){
    Route::post("/getPosts", "ApiController@getPosts")->name("api.getPosts");
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    /**
     * @var  array $guarded
     */
    protected $guarded = [
        'id',
        'created_at',
        'updated_at'
    ];

    public function Post()
	{
		return $this->belongsTo(Post::class);
	}
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CommentRepository;
use App\Repositories\PostRepository;

class CommentController extends Controller
{
    protected $commentRepository;
    protected $postRepository;

    public function __construct(CommentRepository $commentRepository, PostRepository $postRepository)
    {
        $this->commentRepository = $commentRepository;
        $this->postRepository = $postRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('comment.index',[
            'comments' => $this->commentRepository->paginate(5)
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('comment.create',[
            'posts' => $this->postRepository->getAll()
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->commentRepository->create([
                'post_id' => $request->input('post_id'),
                'nickname' => $request->input('nickname'),
                'email' => $request->input('email'),
                'website' => $request->input('website'),
                'comment' => $request->input('comment'),
        ]);

        return view('tpl.msg', [
            'title' => '留言成功',
            'status' => 1,
            'msg' => '留言成功！'
        ]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('comment.show',[
            'comment' => $this->commentRepository->getById($id, 'Post')
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('comment.edit', [
            'posts' => $this->postRepository->getAll(),
            'comment' => $this->commentRepository->getById($id, 'Post')
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->commentRepository->update($id, [
            'post_id' => $request->input('post_id'),
            'nickname' => $request->input('nickname'),
            'email' => $request->input('email'),
            'website' => $request->input('website'),
            'comment' => $request->input('comment'),
        ]);

        return view('tpl.msg', [
            'title' => '修改成功!',
            'status' => 1,
            'msg' => '修改成功!'
        ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->commentRepository->delete($id);

        return view('tpl.msg', [
            'title' => '刪除成功!',
            'status' => 1,
            'msg' => '刪除成功!'
        ]);
    }
}

resources/views/comment/create.blade.php
@extends('tpl.main')

@section('title', 'New Comment')

@section('content')
    <form action="{{ url('/admin/comment') }}" method="post">
        @csrf
        <div class="form-group">
            <label for="PostID">Choose Post:</label>
            <select name="post_id" id="PostID" class="form-control">
                @foreach($posts as $post)
                    <option value="{{ $post->id  }}">{{ $post->title }}</option>
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="NickName">NickName:</label>
            <input type="text" name="nickname" id="NickName" class="form-control" placeholder="Nick Name">
        </div>
        <div class="form-group">
            <label for="Email">Email:</label>
            <input type="text" name="email" id="Email" class="form-control" placeholder="Email">
        </div>
        <div class="form-group">
            <label for="Website">Website:</label>
            <input type="text" name="website" id="Website" class="form-control" placeholder="Website">
        </div>
        <div class="form-group">
            <label for="Comment">Your Comment:</label>
            <textarea name="comment" id="Comment" class="form-control" placeholder="Your Comment" rows="3"></textarea>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </form>
@endsection

resources/views/comment/edit.blade.php
@extends('tpl.main')

@section('title', 'Edit a comment')

@section('content')
    <form action="{{ route('comment.update', [ 'comment' => $comment->id ]) }}" method="post">
        @csrf
        @method('put')
        <div class="form-group">
            <label for="PostID">Choose Post:</label>
            <select name="post_id" id="PostID" class="form-control">
                @foreach($posts as $post)
                    @if($post->id == $comment->post_id)
                        <option value="{{ $post->id  }}" selected>{{ $post->title }}</option>
                    @else
                        <option value="{{ $post->id  }}">{{ $post->title }}</option>
                    @endif
                @endforeach
            </select>
        </div>
        <div class="form-group">
            <label for="NickName">NickName:</label>
            <input type="text" name="nickname" id="NickName" class="form-control" placeholder="Nick Name" value="{{ $comment->nickname }}">
        </div>
        <div class="form-group">
            <label for="Email">Email:</label>
            <input type="text" name="email" id="Email" class="form-control" placeholder="Email" value="{{ $comment->email }}">
        </div>
        <div class="form-group">
            <label for="Website">Website:</label>
            <input type="text" name="website" id="Website" class="form-control" placeholder="Website" value="{{ $comment->website }}">
        </div>
        <div class="form-group">
            <label for="Comment">Your Comment:</label>
            <textarea name="comment" id="Comment" class="form-control" placeholder="Your Comment" rows="3">{{ $comment->comment }}</textarea>
        </div>
        <div class="form-group">
            <label for="Created_at">Created at:</label>
            <input type="text" name="created_at" id="Created_at" class="form-control" placeholder="Website" value="{{ $comment->created_at }}" readonly>
        </div>
        <div class="form-group">
            <label for="Updated_at">Updated at:</label>
            <input type="text" name="updated_at" id="Updated_at" class="form-control" placeholder="Website" value="{{ $comment->updated_at }}" readonly>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">Edit</button>
        </div>
    </form>
@endsection

resources/views/comment/index.blade.php
@extends('tpl.main')

@section('title', 'All Comments')

@section('head')
    <script>
        function deleteCheck()
        {
            return confirm('確認要刪除嗎？');
        }
    </script>
@endsection

@section('content')
    @foreach($comments as $comment)
        <table class="table table-bordered">
            <tr>
                <td>NickName:</td>
                <td>{{ $comment->nickname }}</td>
            </tr>
            <tr>
                <td>Email:</td>
                <td>{{ $comment->email }}</td>
            </tr>
            <tr>
                <td>Website:</td>
                <td>{{ $comment->website }}</td>
            </tr>
            <tr>
                <td>Comment:</td>
                <td>{{ $comment->comment }}</td>
            </tr>
            <tr>
                <td>Created at:</td>
                <td>{{ $comment->created_at }}</td>
            </tr>
            <tr>
                <td>Last updated at:</td>
                <td>{{ $comment->updated_at }}</td>
            </tr>
            <tr>
                <td>Detail:</td>
                <td><a href="{{ route('comment.show', [ 'comment' => $comment->id ]) }}" class="btn btn-info">Detail</a></td>
            </tr>
            <tr>
                <td>Action:</td>
                <td>
                    <form action="{{ route('comment.destroy', [ 'comment' => $comment->id ]) }}" method="post">
                        @csrf
                        @method('delete')
                        <button type="button" onclick="document.location.href='{{ route('comment.edit', [ 'comment' => $comment->id ]) }}';" class="btn btn-warning"><i class="fa fa-edit"></i> 編輯</button>
                        <button type="submit" class="btn btn-danger" onclick="return deleteCheck()"><i class="fa fa-trash"></i> 刪除</button>
                    </form>
                </td>
            </tr>
        </table>
    @endforeach
    {{ $comments->links() }}
@endsection

resources/views/comment/show.blade.php
@extends('tpl.main')

@section('title', 'Single Comment')

@section('content')
    <table class="table table-bordered">
        <tr>
            <td>NickName:</td>
            <td>{{ $comment->nickname }}</td>
        </tr>
        <tr>
            <td>Email:</td>
            <td>{{ $comment->email }}</td>
        </tr>
        <tr>
            <td>Website:</td>
            <td>{{ $comment->website }}</td>
        </tr>
        <tr>
            <td>Comment:</td>
            <td>{{ $comment->comment }}</td>
        </tr>
        <tr>
            <td>Created at:</td>
            <td>{{ $comment->created_at }}</td>
        </tr>
        <tr>
            <td>Last updated at:</td>
            <td>{{ $comment->updated_at }}</td>
        </tr>
    </table>
    <table class="table table-bordered text-center mx-auto w-75">
        <thead class="thead-dark">
            <tr>
                <th colspan="2">Associate Post</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Post ID</td>
                <td>Post Title</td>
            </tr>
            <tr>
                <td>{{ $comment->Post->id }}</td>
                <td><a href="{{ route('post.show', [ 'post' => $comment->Post->id ]) }}" target="_blank">{{ $comment->Post->title }}</a></td>
            </tr>
        </tbody>
    </table>
@endsection